In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/final1/Final/clk_06.csv
/kaggle/input/final1/Final/clk_10.csv
/kaggle/input/final1/Final/imp_07.csv
/kaggle/input/final1/Final/imp_12.csv
/kaggle/input/final1/Final/clk_08.csv
/kaggle/input/final1/Final/imp_11.csv
/kaggle/input/final1/Final/clk_07.csv
/kaggle/input/final1/Final/imp_09.csv
/kaggle/input/final1/Final/imp_10.csv
/kaggle/input/final1/Final/clk_11.csv
/kaggle/input/final1/Final/imp_08.csv
/kaggle/input/final1/Final/clk_12.csv
/kaggle/input/final1/Final/imp_06.csv
/kaggle/input/final1/Final/clk_09.csv
/kaggle/input/user-data/Dataset/clk_06.csv
/kaggle/input/user-data/Dataset/clk_10.csv
/kaggle/input/user-data/Dataset/imp_07.csv
/kaggle/input/user-data/Dataset/conv_11.csv
/kaggle/input/user-data/Dataset/conv_12.csv
/kaggle/input/user-data/Dataset/bid_07.csv
/kaggle/input/user-data/Dataset/conv_10.csv
/kaggle/input/user-data/Dataset/imp_12.csv
/kaggle/input/user-data/Dataset/clk_08.csv
/kaggle/input/user-data/Dataset/imp_11.csv
/kaggle/input/user-data/Dataset/bid_06.csv
/kaggle/input/user-data/Dataset/clk_07.csv
/kaggle/input/user-data/Dataset/imp_09.csv
/kaggle/input/user-data/Dataset/conv_06.csv
/kaggle/input/user-data/Dataset/imp_10.csv
/kaggle/input/user-data/Dataset/clk_11.csv
/kaggle/input/user-data/Dataset/bid_11.csv
/kaggle/input/user-data/Dataset/conv_07.csv
/kaggle/input/user-data/Dataset/imp_08.csv
/kaggle/input/user-data/Dataset/clk_12.csv
/kaggle/input/user-data/Dataset/imp_06.csv
/kaggle/input/user-data/Dataset/conv_09.csv
/kaggle/input/user-data/Dataset/bid_09.csv
/kaggle/input/user-data/Dataset/bid_08.csv
/kaggle/input/user-data/Dataset/clk_09.csv
/kaggle/input/user-data/Dataset/bid_12.csv
/kaggle/input/user-data/Dataset/conv_08.csv
/kaggle/input/user-data/Dataset/bid_10.csv

In [2]:
# bid_df = pd.read_csv(r"/kaggle/input/user-data/Dataset/bid_06.csv", low_memory=True)
imp_df = pd.read_csv(r"/kaggle/input/user-data/Dataset/imp_06.csv", low_memory=True)
clk_df = pd.read_csv(r"/kaggle/input/user-data/Dataset/clk_06.csv", low_memory=True)
conv_df = pd.read_csv(r"/kaggle/input/user-data/Dataset/conv_06.csv", low_memory=True)

In [22]:
# import gc

# del conv_df
# del final_imp_df
# gc.collect()

0

In [10]:
imp_df.head()
# clk_df.head()
# print(imp_df.shape)
# print(imp_df['Logtype'].unique())

,BidID,Timestamp,Logtype,VisitorID,User-Agent,IP,Region,City,Adexchange,Domain,...,Adslotheight,Adslotvisibility,Adslotformat,Adslotfloorprice,CreativeID,Biddingprice,Payingprice,KeypageURL,AdvertiserID,UserInfo
0,5bd0cbeb2f82fb94e56b7dc2e6b77ec,20130606000104252,1,Vhkr1uaROqKsXmb,Mozilla/4.0 (compatible; MSIE 7.0; Windows NT ...,222.220.35.*,308,320,2,eSMvBpa0jqmUagk4JKTI,...,280,2,0,5,13606a7c541dcd9ca1948875a760bb31,238,72,d29e59bf0f7f8243858b8183f14d4412,3358,"13800,10024"
1,faf17eac9cabf1be598f4e75f40d501d,20130606000104253,1,VhL01pk8OTkW3Mc,Mozilla/5.0 (Windows NT 5.1) AppleWebKit/537.1...,58.100.240.*,94,95,1,tK1NTu1YP5scFsf,...,90,0,1,0,d5cecca9a6cbd7a0a48110f1306b26d1,227,108,d29e59bf0f7f8243858b8183f14d4412,3358,"10059,13866,10063,10111"
2,234870d3864ad1852fe04b172f340be3,20130606000104308,1,VhT3La5uDlaywOj,Mozilla/5.0 (Windows NT 5.1) AppleWebKit/537.1...,122.233.40.*,94,95,1,trqRTummPvas1m58uG,...,250,2,1,0,44966cc8da1ed40c95d59e863c8c75f0,300,81,361e128affece850342293213691a043,3386,"10057,10063,10024,13800,13866,10110"
3,20fb85784972aebed3dda8d20ca87afb,20130606000104329,1,VhkSPnNDP8L8eYl,Opera/9.80 (Android; Opera Mini/7.7.33548/29.3...,58.67.157.*,216,217,1,trqRTuS8jZL7FmMs,...,250,0,5,0,d881a6c788e76c2c27ed1ef04f119544,227,89,d29e59bf0f7f8243858b8183f14d4412,3358,"13866,10111"
4,336fa258236a14a81ec0f973716495f,20130606000104371,1,Vhk0Z35ULqFcBZc,Mozilla/4.0 (compatible; MSIE 8.0; Windows NT ...,180.107.223.*,80,85,2,5On-q5uvgN171m58uG,...,280,2,0,5,ff5123fb9333ca095034c62fdaaf51aa,300,5,361e128affece850342293213691a043,3386,"10063,10059,13776,10111"

In [2]:
import gc
file_paths=['/kaggle/input/user-data/Dataset/imp_06.csv',
           '/kaggle/input/user-data/Dataset/imp_07.csv',
           '/kaggle/input/user-data/Dataset/imp_08.csv',
           '/kaggle/input/user-data/Dataset/imp_09.csv',
           '/kaggle/input/user-data/Dataset/imp_10.csv',
           '/kaggle/input/user-data/Dataset/imp_11.csv',
           '/kaggle/input/user-data/Dataset/imp_12.csv']
df_list=[]
for file in file_paths:
    df = pd.read_csv(file)
    df_list.append(df)

final_imp_df = pd.concat(df_list, ignore_index=True)

final_imp_df.columns = ["BidID","Timestamp","Logtype","VisitorID","User-Agent","IP","Region",
                   "City","Adexchange","Domain","URL","AnonymousURLID","AdslotID",
                   "Adslotwidth","Adslotheight",'Adslotvisibility',"Adslotformat",
                   "Adslotfloorprice","CreativeID","Biddingprice","Payingprice","KeypageURL"
                    ,"AdvertiserID","UserInfo"]  
imp_df=final_imp_df
del final_imp_df
gc.collect()

0

In [3]:
file_paths=['/kaggle/input/user-data/Dataset/clk_06.csv',
           '/kaggle/input/user-data/Dataset/clk_07.csv',
           '/kaggle/input/user-data/Dataset/clk_08.csv',
           '/kaggle/input/user-data/Dataset/clk_09.csv',
           '/kaggle/input/user-data/Dataset/clk_10.csv',
           '/kaggle/input/user-data/Dataset/clk_11.csv',
           '/kaggle/input/user-data/Dataset/clk_12.csv']
df_list=[]
for file in file_paths:
    df = pd.read_csv(file)
    df_list.append(df)

final_clk_df = pd.concat(df_list, ignore_index=True)

final_clk_df.columns = ["BidID","Timestamp","Logtype","VisitorID","User-Agent","IP","Region",
                   "City","Adexchange","Domain","URL","AnonymousURLID","AdslotID",
                   "Adslotwidth","Adslotheight",'Adslotvisibility',"Adslotformat",
                   "Adslotfloorprice","CreativeID","Biddingprice","Payingprice","KeypageURL"
                    ,"AdvertiserID","UserInfo"]  

clk_df=final_clk_df
del final_clk_df
gc.collect()

0

In [4]:
imp_list = imp_df['BidID'].to_list()
clk_list = clk_df['BidID'].to_list()
L2 = []

clk_set = set(clk_list)
L2 = [1 if imp in clk_set else 0 for imp in imp_list]

In [5]:
print(len(L2))

12237080

In [6]:
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import FunctionTransformer, StandardScaler, OneHotEncoder
from sklearn.impute import SimpleImputer

In [15]:
print(imp_df.columns)

Index(['BidID', 'Timestamp', 'Logtype', 'VisitorID', 'User-Agent', 'IP',
       'Region', 'City', 'Adexchange', 'Domain', 'URL', 'AnonymousURLID',
       'AdslotID', 'Adslotwidth', 'Adslotheight', 'Adslotvisibility',
       'Adslotformat', 'Adslotfloorprice', 'CreativeID', 'Biddingprice',
       'Payingprice', 'KeypageURL', 'AdvertiserID', 'UserInfo'],
      dtype='object')

In [32]:
# print(len(imp_df['UserInfo'].unique()))
imp_df.head()
#TOC Ki Teacher Se Pucho

,BidID,Timestamp,Logtype,VisitorID,User-Agent,IP,Region,City,Adexchange,Domain,...,Adslotheight,Adslotvisibility,Adslotformat,Adslotfloorprice,CreativeID,Biddingprice,Payingprice,KeypageURL,AdvertiserID,UserInfo
0,5bd0cbeb2f82fb94e56b7dc2e6b77ec,20130606000104252,1,Vhkr1uaROqKsXmb,Mozilla/4.0 (compatible; MSIE 7.0; Windows NT ...,222.220.35.*,308,320,2,eSMvBpa0jqmUagk4JKTI,...,280,2,0,5,13606a7c541dcd9ca1948875a760bb31,238,72,d29e59bf0f7f8243858b8183f14d4412,3358,"13800,10024"
1,faf17eac9cabf1be598f4e75f40d501d,20130606000104253,1,VhL01pk8OTkW3Mc,Mozilla/5.0 (Windows NT 5.1) AppleWebKit/537.1...,58.100.240.*,94,95,1,tK1NTu1YP5scFsf,...,90,0,1,0,d5cecca9a6cbd7a0a48110f1306b26d1,227,108,d29e59bf0f7f8243858b8183f14d4412,3358,"10059,13866,10063,10111"
2,234870d3864ad1852fe04b172f340be3,20130606000104308,1,VhT3La5uDlaywOj,Mozilla/5.0 (Windows NT 5.1) AppleWebKit/537.1...,122.233.40.*,94,95,1,trqRTummPvas1m58uG,...,250,2,1,0,44966cc8da1ed40c95d59e863c8c75f0,300,81,361e128affece850342293213691a043,3386,"10057,10063,10024,13800,13866,10110"
3,20fb85784972aebed3dda8d20ca87afb,20130606000104329,1,VhkSPnNDP8L8eYl,Opera/9.80 (Android; Opera Mini/7.7.33548/29.3...,58.67.157.*,216,217,1,trqRTuS8jZL7FmMs,...,250,0,5,0,d881a6c788e76c2c27ed1ef04f119544,227,89,d29e59bf0f7f8243858b8183f14d4412,3358,"13866,10111"
4,336fa258236a14a81ec0f973716495f,20130606000104371,1,Vhk0Z35ULqFcBZc,Mozilla/4.0 (compatible; MSIE 8.0; Windows NT ...,180.107.223.*,80,85,2,5On-q5uvgN171m58uG,...,280,2,0,5,ff5123fb9333ca095034c62fdaaf51aa,300,5,361e128affece850342293213691a043,3386,"10063,10059,13776,10111"

- For generic Approaches
1) Divide Timestamp to Date, Hours, etc
2) Divide User-Agent to Browser and os
3) Divide UserInfo using Multilabel Binarizer
- For DCN v3 based Approaches
1) Divide Timestamp to Date, Hours, etc
2) Divide User-Agent to Browser, os and type
3) Create Embeddings for the required columns

In [5]:
from datetime import datetime 
import re

imp_df['User-Agent'] = imp_df['User-Agent'].fillna("Unknown")

def extract_os(user_agent):
    os_patterns = {
        'Windows': r'Windows',
        'MacOS': r'Macintosh',
        'iOS': r'iPhone|iPad',
        'Android': r'Android',
        'Linux': r'Linux',
        'Other': r'.*'
    }
    for os, pattern in os_patterns.items():
        if re.search(pattern, user_agent, re.IGNORECASE):
            return os
    return 'Other'

def extract_device(user_agent):
    if re.search(r'Mobile|Android|iPhone|iPad', user_agent, re.IGNORECASE):
        return 'Mobile'
    elif re.search(r'Tablet', user_agent, re.IGNORECASE):
        return 'Tablet'
    else:
        return 'Desktop'

imp_df['OS'] = imp_df['User-Agent'].apply(extract_os)
imp_df['DeviceType'] = imp_df['User-Agent'].apply(extract_device)
imp_df['Browser'] = imp_df['User-Agent'].apply(lambda x: x.split(' ')[0] if ' ' in x else 'Unknown')
imp_df.drop(columns=['User-Agent'], inplace=True)

imp_df['Updated-Agent'] = (imp_df['DeviceType'] + '_' + imp_df['Browser'] + '_' + imp_df['OS'])
imp_df.drop(columns=['OS', 'DeviceType', 'Browser'], inplace=True)

imp_df['Timestamp'] = pd.to_datetime(imp_df['Timestamp'], format='%Y%m%d%H%M%S%f', errors='coerce')
imp_df['Hour'] = imp_df['Timestamp'].dt.hour
imp_df['Weekday'] = imp_df['Timestamp'].dt.weekday
imp_df.drop(columns=['Timestamp'], inplace=True)

imp_df.head()

/usr/local/lib/python3.10/dist-packages/pandas/io/formats/format.py:1458: RuntimeWarning: invalid value encountered in greater
  has_large_values = (abs_vals > 1e6).any()
/usr/local/lib/python3.10/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in less
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()
/usr/local/lib/python3.10/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in greater
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()
/usr/local/lib/python3.10/dist-packages/pandas/io/formats/format.py:1458: RuntimeWarning: invalid value encountered in greater
  has_large_values = (abs_vals > 1e6).any()
/usr/local/lib/python3.10/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in less
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()
/usr/local/lib/python3.10/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in greater
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()

,BidID,Logtype,VisitorID,IP,Region,City,Adexchange,Domain,URL,AnonymousURLID,...,Adslotfloorprice,CreativeID,Biddingprice,Payingprice,KeypageURL,AdvertiserID,UserInfo,Updated-Agent,Hour,Weekday
0,5bd0cbeb2f82fb94e56b7dc2e6b77ec,1,Vhkr1uaROqKsXmb,222.220.35.*,308,320,2,eSMvBpa0jqmUagk4JKTI,15b56f50bbaa689c91ccaf5ed7c97b48,NaN,...,5,13606a7c541dcd9ca1948875a760bb31,238,72,d29e59bf0f7f8243858b8183f14d4412,3358,"13800,10024",Desktop_Mozilla/4.0_Windows,0,3
1,faf17eac9cabf1be598f4e75f40d501d,1,VhL01pk8OTkW3Mc,58.100.240.*,94,95,1,tK1NTu1YP5scFsf,e22930480589abcc1468854cb3403314,NaN,...,0,d5cecca9a6cbd7a0a48110f1306b26d1,227,108,d29e59bf0f7f8243858b8183f14d4412,3358,"10059,13866,10063,10111",Desktop_Mozilla/5.0_Windows,0,3
2,234870d3864ad1852fe04b172f340be3,1,VhT3La5uDlaywOj,122.233.40.*,94,95,1,trqRTummPvas1m58uG,762a1aa930e6f41c969e77226c62f3a7,NaN,...,0,44966cc8da1ed40c95d59e863c8c75f0,300,81,361e128affece850342293213691a043,3386,"10057,10063,10024,13800,13866,10110",Desktop_Mozilla/5.0_Windows,0,3
3,20fb85784972aebed3dda8d20ca87afb,1,VhkSPnNDP8L8eYl,58.67.157.*,216,217,1,trqRTuS8jZL7FmMs,1eb132233cd79996f8abdd03e2de6699,NaN,...,0,d881a6c788e76c2c27ed1ef04f119544,227,89,d29e59bf0f7f8243858b8183f14d4412,3358,"13866,10111",Mobile_Opera/9.80_Android,0,3
4,336fa258236a14a81ec0f973716495f,1,Vhk0Z35ULqFcBZc,180.107.223.*,80,85,2,5On-q5uvgN171m58uG,5d3da31171309d3294daf8835687e5b7,NaN,...,5,ff5123fb9333ca095034c62fdaaf51aa,300,5,361e128affece850342293213691a043,3386,"10063,10059,13776,10111",Desktop_Mozilla/4.0_Windows,0,3

In [11]:
# imp_df['Updated-Agent'][:10]
# imp_df['Hour'].unique()
# imp_df['Weekday'].unique()
# print(imp_df.describe())
# imp_df.info()
imp_df.nunique()

IP                  631255
Region                  35
City                   370
Adexchange               3
Domain               28504
AdslotID            141515
Adslotwidth             13
Adslotheight             7
Adslotvisibility         4
Adslotformat             3
Adslotfloorprice       229
CreativeID              74
AdvertiserID             5
Updated-Agent          732
Hour                    24
Weekday                  7
dtype: int64

In [6]:
cols_to_drop = ["BidID","Logtype","VisitorID","URL","AnonymousURLID","UserInfo","Biddingprice","Payingprice","KeypageURL"]


imp_df.drop(columns = cols_to_drop,inplace = True)

In [7]:
imp_df.head()

,IP,Region,City,Adexchange,Domain,AdslotID,Adslotwidth,Adslotheight,Adslotvisibility,Adslotformat,Adslotfloorprice,CreativeID,AdvertiserID,Updated-Agent,Hour,Weekday
0,222.220.35.*,308,320,2,eSMvBpa0jqmUagk4JKTI,3521017083,336,280,2,0,5,13606a7c541dcd9ca1948875a760bb31,3358,Desktop_Mozilla/4.0_Windows,0,3
1,58.100.240.*,94,95,1,tK1NTu1YP5scFsf,mm_10075660_3500949_11453278,950,90,0,1,0,d5cecca9a6cbd7a0a48110f1306b26d1,3358,Desktop_Mozilla/5.0_Windows,0,3
2,122.233.40.*,94,95,1,trqRTummPvas1m58uG,mm_10058411_2865562_9929053,300,250,2,1,0,44966cc8da1ed40c95d59e863c8c75f0,3386,Desktop_Mozilla/5.0_Windows,0,3
3,58.67.157.*,216,217,1,trqRTuS8jZL7FmMs,mm_40468498_3493773_11415894,300,250,0,5,0,d881a6c788e76c2c27ed1ef04f119544,3358,Mobile_Opera/9.80_Android,0,3
4,180.107.223.*,80,85,2,5On-q5uvgN171m58uG,4017603800,336,280,2,0,5,ff5123fb9333ca095034c62fdaaf51aa,3386,Desktop_Mozilla/4.0_Windows,0,3

In [8]:
# imp_df["Domain"].value_counts()
# for col in ["IP", "Domain", "AdslotID", "CreativeID", "Updated-Agent"]:
#     print(f"{col} Top 10:")
#     print(imp_df[col].value_counts().head(10))
#     print("\n")

gc.collect()

0

# THE FINAL PIPELINE. Whatever changes you want to make to the dataset, try to make it through this

In [13]:
# embedding_config = {
#     "IP": {"type": "categorical", "padding_idx": 0, "oov_idx": 631256, "vocab_size": 631257},
#     "Region": {"type": "categorical", "padding_idx": 0, "oov_idx": 36, "vocab_size": 37},
#     "City": {"type": "categorical", "padding_idx": 0, "oov_idx": 371, "vocab_size": 372},
#     "Adexchange": {"type": "categorical", "padding_idx": 0, "oov_idx": 4, "vocab_size": 5},
#     "Domain": {"type": "categorical", "padding_idx": 0, "oov_idx": 28505, "vocab_size": 28506},
#     "AdslotID": {"type": "categorical", "padding_idx": 0, "oov_idx": 141516, "vocab_size": 141517},
#     "CreativeID": {"type": "categorical", "padding_idx": 0, "oov_idx": 75, "vocab_size": 76},
#     "AdvertiserID": {"type": "categorical", "padding_idx": 0, "oov_idx": 6, "vocab_size": 7},
#     "Updated-Agent": {"type": "categorical", "padding_idx": 0, "oov_idx": 733, "vocab_size": 734},
#     "Adslotvisibility": {"type": "categorical", "padding_idx": 0, "oov_idx": 5, "vocab_size": 6},
#     "Adslotformat": {"type": "categorical", "padding_idx": 0, "oov_idx": 4, "vocab_size": 5},
#     "Hour": {"type": "categorical", "padding_idx": 0, "oov_idx": 25, "vocab_size": 26},
#     "Weekday": {"type": "categorical", "padding_idx": 0, "oov_idx": 8, "vocab_size": 9}
# }

In [9]:
!git clone https://github.com/reczoo/FuxiCTR.git
%cd FuxiCTR
!pip install -r requirements.txt

Cloning into 'FuxiCTR'...
remote: Enumerating objects: 3084, done.
remote: Counting objects: 100% (844/844), done.
remote: Compressing objects: 100% (304/304), done.
remote: Total 3084 (delta 685), reused 551 (delta 540), pack-reused 2240 (from 2)
Receiving objects: 100% (3084/3084), 2.47 MiB | 22.40 MiB/s, done.
Resolving deltas: 100% (1931/1931), done.
/kaggle/working/FuxiCTR
Collecting keras_preprocessing (from -r requirements.txt (line 1))
  Downloading Keras_Preprocessing-1.1.2-py2.py3-none-any.whl.metadata (1.9 kB)
Requirement already satisfied: pandas in /usr/local/lib/python3.10/dist-packages (from -r requirements.txt (line 2)) (2.2.2)
Requirement already satisfied: PyYAML in /usr/local/lib/python3.10/dist-packages (from -r requirements.txt (line 3)) (6.0.2)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.10/dist-packages (from -r requirements.txt (line 4)) (1.2.2)
Requirement already satisfied: numpy in /usr/local/lib/python3.10/dist-packages (from -r requirements.txt (line 5)) (1.26.4)
Requirement already satisfied: h5py in /usr/local/lib/python3.10/dist-packages (from -r requirements.txt (line 6)) (3.12.1)
Requirement already satisfied: tqdm in /usr/local/lib/python3.10/dist-packages (from -r requirements.txt (line 7)) (4.67.1)
Requirement already satisfied: pyarrow in /usr/local/lib/python3.10/dist-packages (from -r requirements.txt (line 8)) (17.0.0)
Collecting polars<=1.0.0 (from -r requirements.txt (line 9))
  Downloading polars-1.0.0-cp38-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (14 kB)
Requirement already satisfied: six>=1.9.0 in /usr/local/lib/python3.10/dist-packages (from keras_preprocessing->-r requirements.txt (line 1)) (1.17.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.10/dist-packages (from pandas->-r requirements.txt (line 2)) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas->-r requirements.txt (line 2)) (2024.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.10/dist-packages (from pandas->-r requirements.txt (line 2)) (2024.2)
Requirement already satisfied: scipy>=1.3.2 in /usr/local/lib/python3.10/dist-packages (from scikit-learn->-r requirements.txt (line 4)) (1.13.1)
Requirement already satisfied: joblib>=1.1.1 in /usr/local/lib/python3.10/dist-packages (from scikit-learn->-r requirements.txt (line 4)) (1.4.2)
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.10/dist-packages (from scikit-learn->-r requirements.txt (line 4)) (3.5.0)
Requirement already satisfied: mkl_fft in /usr/local/lib/python3.10/dist-packages (from numpy->-r requirements.txt (line 5)) (1.3.8)
Requirement already satisfied: mkl_random in /usr/local/lib/python3.10/dist-packages (from numpy->-r requirements.txt (line 5)) (1.2.4)
Requirement already satisfied: mkl_umath in /usr/local/lib/python3.10/dist-packages (from numpy->-r requirements.txt (line 5)) (0.1.1)
Requirement already satisfied: mkl in /usr/local/lib/python3.10/dist-packages (from numpy->-r requirements.txt (line 5)) (2025.0.1)
Requirement already satisfied: tbb4py in /usr/local/lib/python3.10/dist-packages (from numpy->-r requirements.txt (line 5)) (2022.0.0)
Requirement already satisfied: mkl-service in /usr/local/lib/python3.10/dist-packages (from numpy->-r requirements.txt (line 5)) (2.4.1)
Requirement already satisfied: intel-openmp>=2024 in /usr/local/lib/python3.10/dist-packages (from mkl->numpy->-r requirements.txt (line 5)) (2024.2.0)
Requirement already satisfied: tbb==2022.* in /usr/local/lib/python3.10/dist-packages (from mkl->numpy->-r requirements.txt (line 5)) (2022.0.0)
Requirement already satisfied: tcmlib==1.* in /usr/local/lib/python3.10/dist-packages (from tbb==2022.*->mkl->numpy->-r requirements.txt (line 5)) (1.2.0)
Requirement already satisfied: intel-cmplr-lib-rt in /usr/local/lib/python3.10/dist-packages (from mkl_umath->numpy->-r requirements.txt (line 5)) (2024.2.0)
Requirement already satisfied: intel-cmplr-lib-ur==2024.2.0 in /usr/local/lib/python3.10/dist-packages (from intel-openmp>=2024->mkl->numpy->-r requirements.txt (line 5)) (2024.2.0)
Downloading Keras_Preprocessing-1.1.2-py2.py3-none-any.whl (42 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 42.6/42.6 kB 1.9 MB/s eta 0:00:00
Downloading polars-1.0.0-cp38-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (31.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 31.0/31.0 MB 51.8 MB/s eta 0:00:00:00:0100:01
Installing collected packages: polars, keras_preprocessing
  Attempting uninstall: polars
    Found existing installation: polars 1.9.0
    Uninstalling polars-1.9.0:
      Successfully uninstalled polars-1.9.0
Successfully installed keras_preprocessing-1.1.2 polars-1.0.0

In [10]:
!pwd

# from fuxictr.pytorch.models import BaseModel
# from fuxictr.pytorch.layers import FeatureEmbedding
# from fuxictr.pytorch.torch_utils import get_regularizer

/kaggle/working/FuxiCTR

In [12]:
# print(imp_df.columns)
imp_df = imp_df.astype(str)
imp_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12237080 entries, 0 to 12237079
Data columns (total 16 columns):
 #   Column            Dtype
---  ------            -----
 0   IP                object
 1   Region            object
 2   City              object
 3   Adexchange        object
 4   Domain            object
 5   AdslotID          object
 6   Adslotwidth       object
 7   Adslotheight      object
 8   Adslotvisibility  object
 9   Adslotformat      object
 10  Adslotfloorprice  object
 11  CreativeID        object
 12  AdvertiserID      object
 13  Updated-Agent     object
 14  Hour              object
 15  Weekday           object
dtypes: object(16)
memory usage: 1.5+ GB

In [17]:
len(L2)

12237080

In [13]:
gc.collect()

20

In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split

# imp_df['click'] = L2  
# imp_df.info()

train_df, test_df = train_test_split(imp_df, test_size=0.05, random_state=42,stratify = imp_df['click'])

train_df.to_csv('/kaggle/working/train.csv', index=False)
del train_df
gc.collect()
test_df.to_csv('/kaggle/working/test.csv', index=False)
del test_df
gc.collect()

# print("Train and test CSV files saved successfully!")

Using the DATALOADER for the Model

In [ ]:

"""
    DCNv3_tuner_config_iPinYou.yaml 
    Most likely for fune tuning purposes  
"""

# base_config: ./config/
# base_expid: DCNv3_iPinYou_x1
# dataset_id: iPinYou_x1_csv

# tuner_space:
#     model_root: './checkpoints/'
#     batch_size: 4096
#     num_deep_cross_layers: [3, 4, 5]
#     num_shallow_cross_layers: [3, 4, 5]
#     deep_net_dropout: [0.1, 0.2, 0.3]
#     shallow_net_dropout: [0.1, 0.2, 0.3]

###############

"""
    dataset_config.yaml
    Configuring the dataset/ the Dataloader
"""

 0   IP                object
 1   Region            object
 2   City              object
 3   Adexchange        object
 4   Domain            object
 5   AdslotID          object
 6   Adslotwidth       object
 7   Adslotheight      object
 8   Adslotvisibility  object
 9   Adslotformat      object
 10  Adslotfloorprice  object
 11  CreativeID        object
 12  AdvertiserID      object
 13  Updated-Agent     object
 14  Hour              object
 15  Weekday           object

iPinYou_x1_csv:
    data_format: csv
    data_root: ../../../data/
    feature_cols:
    -   active: true
        dtype: str
        name: [IP, Region, City, Adexchange, Domain,
              AdslotID,Adslotwidth,Adslotheight,Adsoltvisibility,Adslotformat,Adslotfloorprice,
              CreativeID, AdvertiserID, Updated-Agent, Hours, Weekday]
        type: categorical
    label_col: {dtype: float, name: click}
    min_categr_count: 2
    test_data: ../../../data/iPinYou/test.csv
    train_data: ../../../data/iPinYou/train.csv
    valid_data: ../../../data/iPinYou/test.csv

###############

"""
    model_config.yaml 
    Model Hyperparams Tuning Definition
    BASE Defines the Interface for variety of Models, 
    DCNv3 model specifications also there
    
"""


Base:
    model_root: './checkpoints/'
    num_workers: 8
    verbose: 1
    early_stop_patience: 2
    pickle_feature_encoder: True
    save_best_only: True
    eval_steps: null
    debug_mode: False
    group_id: null
    use_features: null
    feature_specs: null
    feature_config: null


DCNv3_iPinYou_x1:
    model: DCNv3
    dataset_id: iPinYou_x1_csv
    loss: 'binary_crossentropy'
    metrics: ['logloss', 'AUC']
    task: binary_classification
    optimizer: adam
    learning_rate: 1.e-3
    embedding_regularizer: 1.e-3
    net_regularizer: 0
    batch_size: 4096
    embedding_dim: 16
    num_deep_cross_layers: 3
    num_shallow_cross_layers: 4
    deep_net_dropout: 0.1
    shallow_net_dropout: 0.2
    layer_norm: True
    batch_norm: True
    num_heads: 1
    epochs: 100
    shuffle: True
    seed: 2024
    num_workers: 4
    monitor: {'AUC': 1, 'logloss': 0}
    monitor_mode: 'max'

###############

Model Definition: Uses FuxiCTR Repository to build on the DCNv2 and create Feature MAPS and Embeddings, no need to explicitly create embedddings

In [11]:
import torch
from torch import nn
from fuxictr.pytorch.models import BaseModel
from fuxictr.pytorch.layers import FeatureEmbedding
from fuxictr.pytorch.torch_utils import get_regularizer


class DCNv3(BaseModel):
    def __init__(self,
                 feature_map,
                 model_id="DCNv3",
                 gpu=-1,
                 learning_rate=1e-3,
                 embedding_dim=10,
                 num_deep_cross_layers=4,
                 num_shallow_cross_layers=4,
                 deep_net_dropout=0.1,
                 shallow_net_dropout=0.3,
                 layer_norm=True,
                 batch_norm=False,
                 num_heads=1,
                 embedding_regularizer=None,
                 net_regularizer=None,
                 **kwargs):
        super(DCNv3, self).__init__(feature_map,
                                    model_id=model_id,
                                    gpu=gpu,
                                    embedding_regularizer=embedding_regularizer,
                                    net_regularizer=net_regularizer,
                                    **kwargs)
        self.embedding_layer = MultiHeadFeatureEmbedding(feature_map, embedding_dim * num_heads, num_heads) 
        input_dim = feature_map.sum_emb_out_dim()
        self.ECN = ExponentialCrossNetwork(input_dim=input_dim,
                                           num_cross_layers=num_deep_cross_layers,
                                           net_dropout=deep_net_dropout,
                                           layer_norm=layer_norm,
                                           batch_norm=batch_norm,
                                           num_heads=num_heads)
        self.LCN = LinearCrossNetwork(input_dim=input_dim,
                                      num_cross_layers=num_shallow_cross_layers,
                                      net_dropout=shallow_net_dropout,
                                      layer_norm=layer_norm,
                                      batch_norm=batch_norm,
                                      num_heads=num_heads)
        self.compile(kwargs["optimizer"], kwargs["loss"], learning_rate)
        self.reset_parameters()
        self.model_to_device()

    def forward(self, inputs):
        X = self.get_inputs(inputs)
        feature_emb = self.embedding_layer(X)
        dlogit = self.ECN(feature_emb).mean(dim=1)
        slogit = self.LCN(feature_emb).mean(dim=1)
        logit = (dlogit + slogit) * 0.5
        y_pred = self.output_activation(logit)
        return_dict = {"y_pred": y_pred,
                       "y_d": self.output_activation(dlogit),
                       "y_s": self.output_activation(slogit)}
        return return_dict

    def add_loss(self, inputs):
        return_dict = self.forward(inputs)
        y_true = self.get_labels(inputs)
        y_pred = return_dict["y_pred"]
        y_d = return_dict["y_d"]
        y_s = return_dict["y_s"]
        loss = self.loss_fn(y_pred, y_true, reduction='mean')
        loss_d = self.loss_fn(y_d, y_true, reduction='mean')
        loss_s = self.loss_fn(y_s, y_true, reduction='mean')
        weight_d = loss_d - loss
        weight_s = loss_s - loss
        weight_d = torch.where(weight_d > 0, weight_d, torch.zeros(1).to(weight_d.device))
        weight_s = torch.where(weight_s > 0, weight_s, torch.zeros(1).to(weight_s.device))
        loss = loss + loss_d * weight_d + loss_s * weight_s
        return loss


class MultiHeadFeatureEmbedding(nn.Module):
    def __init__(self, feature_map, embedding_dim, num_heads=2):
        super(MultiHeadFeatureEmbedding, self).__init__()
        self.num_heads = num_heads
        self.embedding_layer = FeatureEmbedding(feature_map, embedding_dim)

    def forward(self, X):  # H = num_heads
        feature_emb = self.embedding_layer(X)  # B × F × D
        multihead_feature_emb = torch.tensor_split(feature_emb, self.num_heads, dim=-1)
        multihead_feature_emb = torch.stack(multihead_feature_emb, dim=1)  # B × H × F × D/H
        multihead_feature_emb1, multihead_feature_emb2 = torch.tensor_split(multihead_feature_emb, 2,
                                                                            dim=-1)  # B × H × F × D/2H
        multihead_feature_emb1, multihead_feature_emb2 = multihead_feature_emb1.flatten(start_dim=2), \
                                                         multihead_feature_emb2.flatten(
                                                             start_dim=2)  # B × H × FD/2H; B × H × FD/2H
        multihead_feature_emb = torch.cat([multihead_feature_emb1, multihead_feature_emb2], dim=-1)
        return multihead_feature_emb  # B × H × FD/H


class ExponentialCrossNetwork(nn.Module):
    def __init__(self,
                 input_dim,
                 num_cross_layers=3,
                 layer_norm=True,
                 batch_norm=False,
                 net_dropout=0.1,
                 num_heads=1):
        super(ExponentialCrossNetwork, self).__init__()
        self.num_cross_layers = num_cross_layers
        self.layer_norm = nn.ModuleList()
        self.batch_norm = nn.ModuleList()
        self.dropout = nn.ModuleList()
        self.w = nn.ModuleList()
        self.b = nn.ParameterList()
        for i in range(num_cross_layers):
            self.w.append(nn.Linear(input_dim, input_dim // 2, bias=False))
            self.b.append(nn.Parameter(torch.zeros((input_dim,))))
            if layer_norm:
                self.layer_norm.append(nn.LayerNorm(input_dim // 2))
            if batch_norm:
                self.batch_norm.append(nn.BatchNorm1d(num_heads))
            if net_dropout > 0:
                self.dropout.append(nn.Dropout(net_dropout))
            nn.init.uniform_(self.b[i].data)
        self.masker = nn.ReLU()
        self.dfc = nn.Linear(input_dim, 1)

    def forward(self, x):
        for i in range(self.num_cross_layers):
            H = self.w[i](x)
            if len(self.batch_norm) > i:
                H = self.batch_norm[i](H)
            if len(self.layer_norm) > i:
                norm_H = self.layer_norm[i](H)
                mask = self.masker(norm_H)
            else:
                mask = self.masker(H)
            H = torch.cat([H, H * mask], dim=-1)
            x = x * (H + self.b[i]) + x
            if len(self.dropout) > i:
                x = self.dropout[i](x)
        logit = self.dfc(x)
        return logit


class LinearCrossNetwork(nn.Module):
    def __init__(self,
                 input_dim,
                 num_cross_layers=3,
                 layer_norm=True,
                 batch_norm=True,
                 net_dropout=0.1,
                 num_heads=1):
        super(LinearCrossNetwork, self).__init__()
        self.num_cross_layers = num_cross_layers
        self.layer_norm = nn.ModuleList()
        self.batch_norm = nn.ModuleList()
        self.dropout = nn.ModuleList()
        self.w = nn.ModuleList()
        self.b = nn.ParameterList()
        for i in range(num_cross_layers):
            self.w.append(nn.Linear(input_dim, input_dim // 2, bias=False))
            self.b.append(nn.Parameter(torch.zeros((input_dim,))))
            if layer_norm:
                self.layer_norm.append(nn.LayerNorm(input_dim // 2))
            if batch_norm:
                self.batch_norm.append(nn.BatchNorm1d(num_heads))
            if net_dropout > 0:
                self.dropout.append(nn.Dropout(net_dropout))
            nn.init.uniform_(self.b[i].data)
        self.masker = nn.ReLU()
        self.sfc = nn.Linear(input_dim, 1)

    def forward(self, x):
        x0 = x
        for i in range(self.num_cross_layers):
            H = self.w[i](x)
            if len(self.batch_norm) > i:
                H = self.batch_norm[i](H)
            if len(self.layer_norm) > i:
                norm_H = self.layer_norm[i](H)
                mask = self.masker(norm_H)
            else:
                mask = self.masker(H)
            H = torch.cat([H, H * mask], dim=-1)
            x = x0 * (H + self.b[i]) + x
            if len(self.dropout) > i:
                x = self.dropout[i](x)
        logit = self.sfc(x)
        return logit

In [33]:
import sys
sys.path.append("/kaggle/working/FuxiCTR")

# Using SMOTE for upsampling

In [ ]:
smote = SMOTE(random_state=42)
X_resampled, y_resampled = smote.fit_resample(X_train, y_train)

print(f"Original class distribution: {y_train.value_counts().to_dict()}")
print(f"Resampled class distribution: {pd.Series(y_resampled).value_counts().to_dict()}")